"use client";

import { useState } from "react";
import { Activity, ArrowUpRight, Route, TimerReset, Waves } from "lucide-react";
import { RANKS, rankIndexForRating } from "@/lib/ranks";
import type { MapDifficultyDetails, MapPatternSegment, MapSectionAnalysis } from "@/lib/map-difficulty";

export type MapAnalysisTimelineData={analyzerVersion:number;rating:number;directionScore:number;distanceScore:number;npsScore:number;staminaIndex:number;activeDurationMs:number;longestHardSectionMs:number;peakJumpNps:number;peakStreamNps:number;peakJumpStrain:number;peakStreamStrain:number;jumpRatio:number;patternSegments:MapPatternSegment[];topSections:MapSectionAnalysis[];details?:MapDifficultyDetails|null};
const clamp=(v:number,min=0,max=12)=>Math.min(max,Math.max(min,v));
const localRating=(strain:number)=>Math.round(clamp(0.45+4.2*Math.log1p(Math.max(0,strain)*1.3))*100)/100;
const time=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`};
const pct=(v:number)=>`${Math.round(Math.max(0,Math.min(1,v))*100)}%`;
const color=(rating:number)=>RANKS[rankIndexForRating(rating)]?.color??RANKS[RANKS.length-1].color;
const name=(p:string)=>p==="stream-lean"?"Stream lean":p==="jump-lean"?"Jump lean":p==="rest"?"Rest":p.charAt(0).toUpperCase()+p.slice(1);
function reason(s:MapPatternSegment){if(s.pattern==="rest")return "Recovery/rest section. It contributes recovery without artificially lowering active-map difficulty.";const parts=[];parts.push(s.averageNps>=10?"high local timing":s.averageNps>=6?"moderate timing":"slower timing");parts.push(s.distance>=.65?"large spacing":s.distance>=.35?"mixed spacing":"compact spacing");parts.push(s.direction>=.6?"sharp reversals":s.direction>=.3?"direction changes":"simple flow");if((s.cheeseRatio??0)>.45)parts.push("low-movement speed pressure discounted");return parts.join(" + ");}

export function MapAnalysisTimeline({analysis,isLegacy}:{analysis:MapAnalysisTimelineData;isLegacy:boolean}){
 const [showAll,setShowAll]=useState(false);const segments=analysis.patternSegments??[];const top=analysis.topSections??[];const details=analysis.details??null;const total=Math.max(1,...segments.map(s=>s.endMs));const visible=showAll?segments:segments.slice(0,24);
 return <section className="ui-panel ui-panel-compact sm:p-8">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="flex items-center gap-2 text-sm uppercase tracking-[0.2em] text-accent"><Activity size={16}/>Difficulty analysis v{analysis.analyzerVersion}</p><h2 className="mt-1 text-2xl font-semibold text-white">Why this map is rated {analysis.rating.toFixed(2)}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-muted">Difficulty v5 reads the raw map notes and combines note-to-note timing, three-note direction changes, logistic movement distance, local NPS, repeated patterns, multi-scale bursts, sustained pressure, recovery, stamina, and whole-map difficulty coverage. Peaks matter, but they cannot define the entire rating by themselves. {isLegacy?"Legacy maps keep this analysis for reference and Challenge progression without awarding rank points.":"Ranked maps use this same analysis for difficulty and maximum mode rewards."}</p></div><div className="rounded-2xl border border-white/10 bg-black/15 px-4 py-3 text-right"><p className="text-xs uppercase text-muted">Final difficulty</p><p className="text-3xl font-black" style={{color:color(analysis.rating)}}>{analysis.rating.toFixed(2)}</p></div></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><Route size={14} className="text-accent"/><p className="mt-2 text-xs uppercase text-muted">Direction</p><p className="text-2xl font-bold text-white">{analysis.directionScore.toFixed(2)} / 10</p><p className="text-xs text-muted">Three-note turns and reversals across the map.</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><ArrowUpRight size={14} className="text-accent"/><p className="mt-2 text-xs uppercase text-muted">Distance</p><p className="text-2xl font-bold text-white">{analysis.distanceScore.toFixed(2)} / 10</p><p className="text-xs text-muted">Logistic spacing curve prevents edge jumps from scaling forever.</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><Waves size={14} className="text-accent"/><p className="mt-2 text-xs uppercase text-muted">Relative NPS</p><p className="text-2xl font-bold text-white">{analysis.npsScore.toFixed(2)} / 10</p><p className="text-xs text-muted">Local note timing; pauses do not dilute active difficulty.</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><TimerReset size={14} className="text-accent"/><p className="mt-2 text-xs uppercase text-muted">Stamina</p><p className="text-2xl font-bold text-white">{pct(analysis.staminaIndex)}</p><p className="text-xs text-muted">Sustained hard runs with recovery taken into account.</p></div></div>
  {details&&<div className="mt-5 space-y-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["Core difficulty",details.coreDifficulty.toFixed(2)],["Sustained difficulty",details.sustainedDifficulty.toFixed(2)],["Peak difficulty",details.peakDifficulty.toFixed(2)],["Stamina difficulty",details.staminaDifficulty.toFixed(2)],["Jump pressure",details.jumpPressure.toFixed(2)],["Stream pressure",details.streamPressure.toFixed(2)],["Tech pressure",details.techPressure.toFixed(2)],["Anti-cheese",pct(1-details.cheeseRatio)]].map(([l,v])=><div key={l} className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-xs uppercase text-muted">{l}</p><p className="mt-1 font-bold text-white">{v}</p></div>)}</div><div className="rounded-2xl border border-white/10 bg-black/15 p-4 text-xs text-muted"><p className="font-bold uppercase tracking-[0.14em]">Whole-map distribution</p><p className="mt-2 text-white">Easy {pct(details.coverage.easy)} · Moderate {pct(details.coverage.moderate)} · Hard {pct(details.coverage.hard)} · Peak {pct(details.coverage.peak)}</p><p className="mt-1">Window pressure: 0.5s {details.windows.micro.toFixed(2)} · 1.5s {details.windows.short.toFixed(2)} · 6s {details.windows.medium.toFixed(2)} · 18s {details.windows.long.toFixed(2)} · consistency {pct(details.difficultyConsistency)} · active duty {pct(details.activeDuty)} · recovery {pct(details.recoveryRatio)}</p></div></div>}
  <div className="mt-6 rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-xs font-bold uppercase text-muted">Full map timeline</p><div className="mt-4 flex h-14 overflow-hidden rounded-xl border border-white/10 bg-black/30">{segments.map((s,i)=>{const r=s.pattern==="rest"?0:localRating(s.averageStrain);return <div key={`${s.startMs}-${i}`} title={`${time(s.startMs)}–${time(s.endMs)} · ${name(s.pattern)} · ${r?r.toFixed(2):"rest"}`} style={{width:`${Math.max(.02,(s.endMs-s.startMs)/total*100)}%`,background:s.pattern==="rest"?"rgba(255,255,255,.035)":color(r),opacity:s.pattern==="rest"?1:.78}}/>})}</div><div className="mt-2 flex justify-between text-xs text-muted"><span>0:00</span><span>{time(total/2)}</span><span>{time(total)}</span></div></div>
  <div className="mt-6 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-xs font-bold uppercase text-muted">Pattern sections</p><div className="mt-3 space-y-2">{visible.map((s,i)=><div key={`${s.startMs}-${i}`} className="rounded-xl border border-white/8 bg-white/[0.025] p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold text-white">{time(s.startMs)}–{time(s.endMs)} · {name(s.pattern)}</p><p className="mt-1 text-xs leading-5 text-muted">{reason(s)}</p></div>{s.pattern!=="rest"&&<p className="font-black" style={{color:color(localRating(s.averageStrain))}}>{localRating(s.averageStrain).toFixed(2)}</p>}</div></div>)}</div>{segments.length>24&&<button onClick={()=>setShowAll(v=>!v)} className="mt-3 rounded-full border border-accent/30 px-4 py-2 text-xs text-white">{showAll?"Show first 24":`Show all ${segments.length}`}</button>}</div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-xs font-bold uppercase text-muted">Hardest windows</p><div className="mt-3 space-y-2">{top.slice(0,10).map((s,i)=><div key={`${s.startMs}-${i}`} className="rounded-xl border border-white/8 p-3"><div className="flex justify-between"><div><p className="text-sm font-semibold text-white">#{i+1} · {time(s.startMs)}–{time(s.endMs)}</p><p className="text-xs text-muted">{name(s.pattern)} · {s.nps.toFixed(2)} NPS · distance {(s.distance*10).toFixed(1)}/10 · direction {(s.direction*10).toFixed(1)}/10</p></div><p className="font-black" style={{color:color(localRating(s.strain))}}>{localRating(s.strain).toFixed(2)}</p></div></div>)}</div></div></div>
 </section>;
}
