"use client";

import { useEffect, useMemo, useState } from "react";
import type { ComponentProps } from "react";
import { SlidersHorizontal } from "lucide-react";
import { MapsBrowser } from "@/components/maps/maps-browser";

type SortKey = "rating" | "name" | "mapper" | "artist" | "length" | "notes" | "rhp";
type Direction = "asc" | "desc";
type ScoreFilter = "all" | "scored" | "unscored";
type SavedMapFilters = { sortKey: SortKey; direction: Direction; scoreFilter: ScoreFilter; showUnranked: boolean; showLegacy: boolean };
export type ModeScoreMap = Record<string, { lock: number; spin: number; vr: number }>;
const FILTER_STORAGE_KEY = "rhythians:maps:filters:v1";
function textValue(value: string | null | undefined) { return (value ?? "").trim().toLowerCase(); }
function isSavedMapFilters(value: unknown): value is SavedMapFilters { if (!value || typeof value !== "object") return false; const filters = value as Partial<SavedMapFilters>; return (filters.sortKey === "rating" || filters.sortKey === "name" || filters.sortKey === "mapper" || filters.sortKey === "artist" || filters.sortKey === "length" || filters.sortKey === "notes" || filters.sortKey === "rhp") && (filters.direction === "asc" || filters.direction === "desc") && (filters.scoreFilter === "all" || filters.scoreFilter === "scored" || filters.scoreFilter === "unscored") && typeof filters.showUnranked === "boolean" && typeof filters.showLegacy === "boolean"; }

export function MapsSortControlsPersisted({ maps, rankInfo, userRhp, currentUserId, modeScores }: ComponentProps<typeof MapsBrowser> & { modeScores: ModeScoreMap }) {
  const [sortKey, setSortKey] = useState<SortKey>("rating"); const [direction, setDirection] = useState<Direction>("asc"); const [scoreFilter, setScoreFilter] = useState<ScoreFilter>("all"); const [showUnranked, setShowUnranked] = useState(false); const [showLegacy, setShowLegacy] = useState(false);
  useEffect(() => { try { const raw = window.localStorage.getItem(FILTER_STORAGE_KEY); if (!raw) return; const saved: unknown = JSON.parse(raw); if (!isSavedMapFilters(saved)) return; setSortKey(saved.sortKey); setDirection(saved.direction); setScoreFilter(saved.scoreFilter); setShowUnranked(saved.showUnranked); setShowLegacy(saved.showLegacy); } catch {} }, []);
  useEffect(() => { try { const filters: SavedMapFilters = { sortKey, direction, scoreFilter, showUnranked, showLegacy }; window.localStorage.setItem(FILTER_STORAGE_KEY, JSON.stringify(filters)); } catch {} }, [sortKey, direction, scoreFilter, showUnranked, showLegacy]);
  const filteredMaps = useMemo(() => maps.filter((map) => { if (!map.isLegacy && !map.isRanked && !showUnranked) return false; if (scoreFilter === "scored") return map.hasScore || Boolean(map.completion?.passed); if (scoreFilter === "unscored") return !(map.hasScore || Boolean(map.completion?.passed)); return true; }).sort((a, b) => { let result = 0; if (sortKey === "rating") result = (a.rating ?? -Infinity) - (b.rating ?? -Infinity); if (sortKey === "name") result = textValue(a.title).localeCompare(textValue(b.title)); if (sortKey === "mapper") result = textValue(a.mapperName ?? a.submittedBy?.displayName ?? a.submittedBy?.username).localeCompare(textValue(b.mapperName ?? b.submittedBy?.displayName ?? b.submittedBy?.username)); if (sortKey === "artist") result = textValue(a.artist).localeCompare(textValue(b.artist)); if (sortKey === "length") result = (a.length ?? -Infinity) - (b.length ?? -Infinity); if (sortKey === "notes") result = (a.noteCount ?? -Infinity) - (b.noteCount ?? -Infinity); if (sortKey === "rhp") result = (a.rating ?? -Infinity) - (b.rating ?? -Infinity); return direction === "asc" ? result : -result; }), [maps, sortKey, direction, scoreFilter, showUnranked]);
  return <div className="space-y-4"><div className="flex flex-col gap-3 rounded-3xl border border-border bg-surface/95 p-4 shadow-glow"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-semibold text-white"><SlidersHorizontal size={16} className="text-accent" /> Map filters & sorting</div><div className="flex flex-wrap gap-2"><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-border bg-background/60 px-4 py-2.5"><input type="checkbox" checked={showUnranked} onChange={(event) => setShowUnranked(event.target.checked)} className="h-4 w-4 accent-accent" /><span className="text-sm font-semibold text-white">Show unranked maps</span></label><label className="flex cursor-pointer items-center gap-3 rounded-2xl border border-border bg-background/60 px-4 py-2.5"><input type="checkbox" checked={showLegacy} onChange={(event) => setShowLegacy(event.target.checked)} className="h-4 w-4 accent-accent" /><span className="text-sm font-semibold text-white">Show legacy maps</span></label></div></div><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1.5 text-xs font-semibold uppercase tracking-[0.14em] text-muted">Sort by<select value={sortKey} onChange={(event) => setSortKey(event.target.value as SortKey)} className="min-w-40 rounded-xl border border-border bg-background/70 px-3 py-2 text-sm font-normal normal-case tracking-normal text-white focus:border-accent/50 focus:outline-none"><option value="rating">Rating</option><option value="name">Map name</option><option value="mapper">Mapper</option><option value="artist">Artist</option><option value="length">Length</option><option value="notes">Notes</option><option value="rhp">RHP value</option></select></label><label className="grid gap-1.5 text-xs font-semibold uppercase tracking-[0.14em] text-muted">Order<select value={direction} onChange={(event) => setDirection(event.target.value as Direction)} className="min-w-32 rounded-xl border border-border bg-background/70 px-3 py-2 text-sm font-normal normal-case tracking-normal text-white focus:border-accent/50 focus:outline-none"><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><label className="grid gap-1.5 text-xs font-semibold uppercase tracking-[0.14em] text-muted">Scores<select value={scoreFilter} onChange={(event) => setScoreFilter(event.target.value as ScoreFilter)} className="min-w-32 rounded-xl border border-border bg-background/70 px-3 py-2 text-sm font-normal normal-case tracking-normal text-white focus:border-accent/50 focus:outline-none"><option value="all">All maps</option><option value="scored">Already scored</option><option value="unscored">Not scored</option></select></label></div></div><MapsBrowser maps={filteredMaps} rankInfo={rankInfo} userRhp={userRhp} currentUserId={currentUserId} showLegacy={showLegacy} onShowLegacyChange={setShowLegacy} modeScores={modeScores} /></div>;
}
