import Link from "next/link";
import { MessageCircle } from "lucide-react";
import { prisma } from "@/lib/db";
import { getSessionUser } from "@/lib/auth";
import { getAvatarUrl } from "@/lib/avatar";
import { UserTags } from "@/components/user-tags";
import { FlagIcon } from "@/components/flag-icon";
import { FriendButton } from "@/components/friend-button";
import { ReportButton } from "@/components/report-button";
import { RhythiaConnect } from "@/components/rhythia-connect";
import { RhythiaStats } from "@/components/rhythia-stats";
import { getRhythiaStatus } from "@/lib/rhythia-status";
import { RankProgress } from "@/components/rank-progress";
import { getUserGlobalRank } from "@/lib/maps-legacy";
import { RhythiaVerifiedBadge } from "@/components/rhythia-verified-badge";
import { ProfileScoreRefresh } from "@/components/profile-score-refresh";
import { getUserCategoryLevels } from "@/lib/categories";
import { getUserChallengeLevel } from "@/lib/challenge";

export const dynamic = "force-dynamic";
