import Link from "next/link";
import { ExternalLink, MessageCircle } from "lucide-react";
import { prisma } from "@/lib/db";
import { getSessionUser } from "@/lib/auth";
import { getAvatarUrl } from "@/lib/avatar";
import { UserTags } from "@/components/user-tags";
import { UserName } from "@/components/user-name";
import { ProfileTagEditor } from "@/components/profile-tag-editor";
import { ProfileShare } from "@/components/profile-share";
import { ProfileBattleButton } from "@/components/profile-battle-button";
import { FlagIcon } from "@/components/flag-icon";
import { FriendButton } from "@/components/friend-button";
import { ReportButton } from "@/components/report-button";
import { RhythiaConnect } from "@/components/rhythia-connect";
import { RhythiaStats } from "@/components/rhythia-stats";
import { getRhythiaStatus } from "@/lib/rhythia-status";
import { getUserGlobalRank } from "@/lib/maps-legacy";
import { RhythiaVerifiedBadge } from "@/components/rhythia-verified-badge";
import { getUserCategoryLevels } from "@/lib/categories";
import { getUserChallengeLevel } from "@/lib/challenge";
import { RhythKitRecentCompletions } from "@/components/rhythkit-recent-completions";
import { getReferralProgress } from "@/lib/referrals";
import { getRankInfo } from "@/lib/ranks";
import { RankIcon } from "@/components/rank-icon";
import { ModeRankCards } from "@/components/mode-rank-progress";
import { syncUserModeScores, type ModePoints } from "@/lib/rhythia-mode-points";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ username: string }> };
function loadProfileUser(username: string) { return prisma.user.findFirst({ where: { profileHandle: username }, include: { clips: { where: { status: "approved" }, orderBy: { createdAt: "desc" }, include: { category: true, reviewedBy: { select: { username: true, displayName: true } } } }, articleRevisions: true, roles: { include: { role: true } }, playerRank: true, userTags: { include: { tag: true } }, rhythiaProfile: true } }); }

export default async function ProfilePage({ params }: Props) {
  const { username } = await params; const currentUser = await getSessionUser(); let user: Awaited<ReturnType<typeof loadProfileUser>> | null = null;
  try { user = await loadProfileUser(username); } catch { const bare = await prisma.user.findFirst({ where: { profileHandle: username }, include: { roles: { include: { role: true } } } }); if (bare) user = { ...bare, clips: [], articleRevisions: [], playerRank: null, userTags: [], rhythiaProfile: null } as Awaited<ReturnType<typeof loadProfileUser>>; }
  if (!user) return <p className="rounded-3xl border border-border bg-surface/95 p-8 text-muted">Profile not found.</p>;
  const isOwnProfile = currentUser?.id === user.id; const isCoach = user.userTags.some((entry) => entry.tag.slug === "rhythian-coach"); const avatarUrl = getAvatarUrl(user, 256);
  const modeSync = user.rhythiaProfile ? await syncUserModeScores(user.id).catch(() => null) : null;
  const modePoints: ModePoints = modeSync ? { lock: modeSync.rpl, spin: modeSync.rps, vr: modeSync.rpv } : { lock: 0, spin: 0, vr: 0 };
  const [rankResult, categoryResult, challengeResult, titleResult, selectedTagResult] = await Promise.allSettled([getUserGlobalRank(user.id), getUserCategoryLevels(user.id), getUserChallengeLevel(user.id), prisma.$queryRawUnsafe<Array<{ title: string; color: string; neon: boolean }>>('SELECT "title", "color", "neon" FROM "UserProfileTitle" WHERE "userId" = $1 LIMIT 1', user.id), prisma.$queryRawUnsafe<Array<{ tagId: string }>>('SELECT "tagId" FROM "UserProfileTag" WHERE "userId" = $1 ORDER BY "position" ASC', user.id)]);
  const globalRank = rankResult.status === "fulfilled" ? rankResult.value : null; const categoryLevels = categoryResult.status === "fulfilled" ? categoryResult.value : []; const challengeLevel = challengeResult.status === "fulfilled" ? challengeResult.value : 0; const profileTitle = titleResult.status === "fulfilled" ? titleResult.value[0] ?? null : null; const selectedTagIds = selectedTagResult.status === "fulfilled" ? selectedTagResult.value.map((entry) => entry.tagId) : []; const selectedTags = selectedTagIds.map((id) => user.userTags.find((entry) => entry.tagId === id)).filter((entry): entry is NonNullable<typeof entry> => Boolean(entry)); const editableTags = user.userTags.filter((entry) => entry.tag.slug !== "rhythian-coach" && entry.tag.slug !== "contributor"); const editableSelectedTagIds = selectedTags.filter((entry) => entry.tag.slug !== "rhythian-coach" && entry.tag.slug !== "contributor").map((entry) => entry.tagId); const referralProgress = isOwnProfile ? await getReferralProgress(user.id) : null;
  let presence: { isOnline: boolean; lastActiveAt: Date | null } | null = null; if (user.rhythiaProfile) presence = await getRhythiaStatus(user.rhythiaProfile).catch(() => null); let presenceLabel = "Offline"; if (presence?.lastActiveAt) { const seconds = Math.floor((Date.now() - presence.lastActiveAt.getTime()) / 1000); if (seconds < 60) presenceLabel = "Active now"; else if (seconds < 3600) presenceLabel = `Active ${Math.floor(seconds / 60)}m ago`; else if (seconds < 86400) presenceLabel = `Active ${Math.floor(seconds / 3600)}h ago`; else if (seconds < 2592000) presenceLabel = `Active ${Math.floor(seconds / 86400)}d ago`; else presenceLabel = `Last seen ${presence.lastActiveAt.toLocaleDateString()}`; } else presenceLabel = "Never seen online";
  const titleStyle = profileTitle?.neon ? { color: profileTitle.color, textShadow: `0 0 5px ${profileTitle.color}, 0 0 14px ${profileTitle.color}, 0 0 28px ${profileTitle.color}` } : profileTitle ? { color: profileTitle.color } : undefined;
  const mainRank = getRankInfo(user.rhp);
  return <div className="space-y-7">
    <section className="rounded-[2rem] border border-border bg-surface/95 p-5 shadow-glow sm:p-7">
      <div className="grid gap-7 xl:grid-cols-[minmax(330px,0.78fr)_minmax(0,1.22fr)]">
        <div className="flex min-h-[430px] flex-col rounded-3xl border border-white/10 bg-[linear-gradient(165deg,rgba(124,143,240,0.08),rgba(0,0,0,0.12))] p-5 sm:p-6">
          <div className="flex items-start gap-5">{avatarUrl ? <img src={avatarUrl} alt={`${user.username}'s avatar`} className="h-24 w-24 shrink-0 rounded-3xl border-2 border-accent/25 object-cover" /> : <div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-3xl border-2 border-accent/25 bg-accent/10 text-3xl font-bold text-accent">{user.username.charAt(0).toUpperCase()}</div>}<div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-[0.28em] text-accent">Profile</p><h1 className="mt-2 flex flex-wrap items-center gap-2 text-3xl font-semibold tracking-[-0.03em] text-white"><UserName username={user.displayName ?? user.username} isCoach={isCoach} />{user.rhythiaProfile?.flag && <FlagIcon flag={user.rhythiaProfile.flag} country={user.rhythiaProfile.country} size="md" />}{user.rhythiaVerified && <RhythiaVerifiedBadge size="sm" />}{user.rhythiaProfile && presence && <span title={presenceLabel} className={`inline-flex items-center gap-1.5 rounded-full border px-2 py-1 text-[11px] font-semibold ${presence.isOnline ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : "border-red-400/25 bg-red-400/10 text-red-300"}`}><span className={`h-1.5 w-1.5 rounded-full ${presence.isOnline ? "bg-emerald-400" : "bg-red-400/70"}`} />{presence.isOnline ? "Online" : "Offline"}</span>}</h1><p className="mt-1 text-sm text-muted">@{user.profileHandle}</p>{profileTitle && <p className="mt-2 text-sm font-semibold" style={titleStyle}>{profileTitle.title}</p>}</div></div>
          {selectedTags.length > 0 && <div className="mt-6"><UserTags tags={selectedTags} size="md" /></div>}
          {user.bio && <p className="mt-6 text-sm leading-7 text-muted">{user.bio}</p>}
          <div className="mt-6 grid gap-3 sm:grid-cols-2">{user.rhythiaProfile && <a href={user.rhythiaProfile.profileUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white transition hover:border-accent/30 hover:bg-white/10"><ExternalLink size={16} /> Rhythia profile</a>}{isOwnProfile && <RhythiaConnect connectedUrl={user.rhythiaProfile?.profileUrl} />}</div>
          <div className="mt-auto border-t border-white/10 pt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted">Member since</p><p className="mt-1 text-sm font-semibold text-white">{user.joinedAt.toLocaleDateString()}</p></div>{isOwnProfile && referralProgress && <ProfileShare userId={user.id} progress={referralProgress.count} earned={referralProgress.earned} />}</div></div>
        </div>

        <div className="space-y-5">
          <div className="grid gap-4 md:grid-cols-[minmax(0,1.25fr)_minmax(220px,0.75fr)]"><div className="rounded-3xl border border-accent/20 bg-accent/10 p-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">Total RHP</p><div className="mt-2 flex items-end gap-3"><p className="text-4xl font-bold tabular-nums text-white">{user.rhp.toLocaleString()}</p><span className="pb-1 text-sm font-semibold" style={{ color: mainRank.color }}>{mainRank.isExpert ? "Expert" : `${mainRank.name} ${mainRank.tier}`}</span></div><div className="mt-3 flex items-center gap-3"><RankIcon rank={mainRank} size={40} /><div><p className="text-xs text-muted">Global position</p><p className="text-sm font-semibold text-white">{globalRank != null ? `#${globalRank.toLocaleString()}` : "—"}</p></div></div></div><div className="rounded-3xl border border-violet-400/15 bg-violet-400/[0.06] p-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-300">Challenge</p><p className="mt-2 text-4xl font-bold text-white">{challengeLevel}</p><p className="mt-1 text-sm text-muted">Current challenge level</p></div></div>
          <section className="rounded-3xl border border-white/10 bg-black/15 p-4 sm:p-5"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">Game mode ranks</p><p className="mt-1 text-sm text-muted">Each score earns points only for the mode it was played in. RPL + RPS + RPV contribute to total RHP.</p></div><ModeRankCards points={modePoints} /></section>
          <div className="flex flex-wrap gap-2">{!isOwnProfile && <><FriendButton userId={user.id} /><ProfileBattleButton userId={user.id} /><Link href={`/messages?user=${encodeURIComponent(user.profileHandle)}`} className="inline-flex items-center justify-center gap-2 rounded-full border border-border bg-white/5 px-5 py-2.5 text-sm font-semibold text-white transition hover:border-accent/40"><MessageCircle size={16} /> Message</Link></>}{currentUser && !isOwnProfile && <ReportButton targetType="user" targetId={user.id} targetLabel={user.username} />}</div>
        </div>
      </div>
    </section>
    {isOwnProfile && <ProfileTagEditor tags={editableTags.map((entry) => ({ id: entry.tagId, name: entry.tag.name, slug: entry.tag.slug }))} selected={editableSelectedTagIds} />}
    {user.rhythiaProfile && <RhythiaStats profile={user.rhythiaProfile} />}
    <RhythKitRecentCompletions userId={user.id} />
    <section className="rounded-[2rem] border border-border bg-surface/95 p-5 shadow-glow sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[0.28em] text-accent">Challenge categories</p><h2 className="mt-2 text-2xl font-semibold text-white">Skill category levels</h2></div><Link href="/categories" className="inline-flex items-center gap-2 rounded-full border border-accent/40 bg-accent/10 px-4 py-2 text-sm font-semibold text-white transition hover:bg-accent/20">View categories</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{categoryLevels.map(({ category, level }) => <div key={category} className="rounded-2xl border border-white/10 bg-black/15 p-4 text-center"><p className="text-xs uppercase tracking-[0.18em] text-muted">{category === "off_grid" ? "Off Grid" : category.charAt(0).toUpperCase() + category.slice(1)}</p><p className="mt-2 text-2xl font-bold text-white">Level {level}</p></div>)}</div></section>
    <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[0.28em] text-accent">Clips</p><h2 className="mt-1 text-2xl font-semibold text-white">Approved clips from this creator</h2></div><p className="text-sm text-muted">{user.clips.length} approved clip{user.clips.length === 1 ? "" : "s"}</p></div>{user.clips.length === 0 ? <div className="rounded-3xl border border-border bg-background/80 p-8 text-sm text-muted">No approved clips are visible yet.</div> : <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{user.clips.map((clip) => <Link key={clip.id} href={`/clips/${clip.id}`} className="overflow-hidden rounded-3xl border border-border bg-surface/95 p-5 transition hover:-translate-y-0.5 hover:border-accent/40"><div className="h-40 rounded-3xl bg-white/5" /><div className="mt-4"><p className="text-sm uppercase tracking-[0.24em] text-accent">{clip.category?.name ?? "Uncategorized"}</p><h3 className="mt-3 text-lg font-semibold text-white">{clip.title}</h3>{clip.reviewedBy && <p className="mt-2 text-xs text-muted">Approved by <span className="font-semibold text-white">{clip.reviewedBy.displayName ?? clip.reviewedBy.username}</span></p>}<p className="mt-2 text-sm text-muted">{clip.createdAt.toLocaleDateString()}</p></div></Link>)}</div>}</section>
  </div>;
}
