import { LockKeyhole, Move, Scan } from "lucide-react";
import { RankIcon } from "@/components/rank-icon";
import { MODE_RULES, modeRankInfo, type ModeKey, type ModePoints } from "@/lib/rhythia-mode-points";

const icons = { lock: LockKeyhole, spin: Move, vr: Scan };
function modeLabel(info: ReturnType<typeof modeRankInfo>) { return info.isExpert ? "Expert" : `${info.name} ${info.tier}`; }

export function ModeRankCards({ points }: { points: ModePoints }) {
  return <div className="grid gap-4 md:grid-cols-3">{(["lock", "spin", "vr"] as ModeKey[]).map((mode) => { const rule = MODE_RULES[mode]; const info = modeRankInfo(points[mode], mode); const Icon = icons[mode]; return <div key={mode} className="rounded-3xl border border-white/10 bg-black/15 p-5 text-center transition hover:-translate-y-0.5 hover:border-accent/25"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-white/5"><RankIcon rank={info} size={54} /></div><div className="mt-3 flex items-center justify-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-muted"><Icon size={14} /> {rule.short}</div><p className="mt-2 text-lg font-semibold text-white" style={{ color: info.color }}>{modeLabel(info)}</p><p className="mt-1 text-2xl font-bold tabular-nums text-white">{points[mode].toLocaleString()} <span className="text-xs font-semibold text-muted">{rule.short}</span></p></div>; })}</div>;
}

export function ModeRankProgressBars({ points }: { points: ModePoints }) {
  return <div className="grid gap-3 md:grid-cols-3">{(["lock", "spin", "vr"] as ModeKey[]).map((mode) => { const rule = MODE_RULES[mode]; const info = modeRankInfo(points[mode], mode); const Icon = icons[mode]; const percent = info.isExpert && info.tier === 5 ? 100 : Math.round(info.progressToNextTier * 100); const next = info.isExpert && info.tier === 5 ? "MAX" : `${Math.max(0, info.nextTierStart - points[mode]).toLocaleString()} ${rule.short} to next tier`; return <div key={mode} className="rounded-2xl border border-white/10 bg-black/15 p-3.5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><RankIcon rank={info} size={32} /><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-muted">{rule.short}</p><p className="text-sm font-semibold" style={{ color: info.color }}>{modeLabel(info)}</p></div></div><div className="text-right"><p className="text-sm font-bold text-white">{points[mode].toLocaleString()}</p><p className="text-[10px] text-muted">/ {info.isExpert && info.tier === 5 ? "MAX" : info.nextTierStart.toLocaleString()}</p></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full transition-all" style={{ width: `${Math.max(2, percent)}%`, background: `linear-gradient(90deg, ${info.color}66, ${info.color})` }} /></div><div className="mt-2 flex items-center justify-between text-[10px] text-muted"><span className="flex items-center gap-1"><Icon size={11} /> {rule.label}</span><span>{next}</span></div></div>; })}</div>;
}
