import { RANKS, RANK_TIERS, getRankInfo, rankTierBounds } from "@/lib/ranks";
import { MODE_RULES } from "@/lib/rhythia-mode-rules";
import { RankIcon } from "@/components/rank-icon";

const modes = [
  { key: "lock", name: "RPL", label: "Lock", scale: MODE_RULES.lock.rankScale, multiplier: MODE_RULES.lock.rewardMultiplier },
  { key: "spin", name: "RPS", label: "Spin", scale: MODE_RULES.spin.rankScale, multiplier: MODE_RULES.spin.rewardMultiplier },
  { key: "vr", name: "RPV", label: "VR", scale: MODE_RULES.vr.rankScale, multiplier: MODE_RULES.vr.rewardMultiplier },
];

export default function AboutRankingPage() {
  return <div className="space-y-8">
    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><p className="text-sm uppercase tracking-[0.3em] text-accent">Ranking system v7</p><h1 className="mt-3 text-3xl font-semibold text-white">Analyzed maps. Analyzed passes.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted">Rhythians ranks players from verified passes on analyzed Rhythia maps. RPL measures Lock, RPS measures Spin, RPV measures VR, and RHP is the exact combined total of those three earned point pools.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Overall RHP ladder</h2><p className="mt-2 text-sm leading-7 text-muted">Copper through Master each have five tiers. Expert is the final rank. The map analyzer assigns every eligible map a difficulty rating, and the rank ladder uses those analyzed ratings rather than Rhythia star values.</p><div className="mt-6 overflow-hidden rounded-2xl border border-border"><div className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-3">{RANKS.map(rank => { const next = RANKS[rank.index + 1]; const tierIcons = rank.index === RANKS.length - 1 ? [<RankIcon key="expert" rank={getRankInfo(rank.minRhp)} size={58}/>] : Array.from({ length: RANK_TIERS }, (_, index) => <RankIcon key={index} rank={getRankInfo(rankTierBounds(rank.index, index + 1).start)} size={42}/>); return <div key={rank.name} className="bg-surface p-5"><div className="flex items-center gap-1">{tierIcons}</div><p className="mt-3 text-sm font-semibold" style={{ color: rank.color }}>{rank.name}</p><p className="mt-2 text-xs text-muted">{rank.minRhp.toLocaleString()}{next ? ` – ${(next.minRhp - 1).toLocaleString()}` : "+"} RHP</p><p className="mt-1 text-xs text-muted">Map rating {rank.rangeMin.toFixed(2)} – {rank.rangeMax.toFixed(2)}</p><p className="mt-2 text-[11px] text-muted">{next ? `${RANK_TIERS} dynamic tiers` : "Final rank · no numbered tiers"}</p></div>; })}</div></div></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">RPL, RPS and RPV</h2><p className="mt-2 text-sm leading-7 text-muted">A passing score contributes only to the camera mode it was played in. Spin and VR use slightly larger reward multipliers because their control requirements differ from Lock, while each mode ladder uses a smaller threshold scale than the combined RHP ladder.</p><div className="mt-5 grid gap-4 md:grid-cols-3">{modes.map(mode => <div key={mode.key} className="rounded-2xl border border-border bg-background/70 p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-accent">{mode.name}</p><h3 className="mt-2 text-lg font-semibold text-white">{mode.label}</h3><p className="mt-2 text-sm text-muted">Reward multiplier: {mode.multiplier.toFixed(2)}×</p><p className="mt-1 text-xs text-muted">Rank scale: {(mode.scale * 100).toFixed(0)}% of the overall ladder.</p></div>)}</div></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Only Ranked and Legacy maps award points</h2><p className="mt-2 text-sm leading-7 text-muted">A map must be a Rhythia Ranked or Legacy map, successfully analyzed by the current map analyzer, pass the rankability checks, and be point-eligible. Unranked maps can still be analyzed for information, but they cannot award RPL, RPS, RPV or RHP.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">How a pass is scored</h2><p className="mt-2 text-sm leading-7 text-muted">The map analyzer first calculates the maximum reward for the exact map, camera mode and play speed. A verified pass can earn that full amount. Ranking v7 then checks the replay when Rhythia provides one and compares the player&apos;s cursor timeline with the exact analyzed map notes.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-border bg-background/70 p-5"><p className="font-semibold text-white">1. Exact map</p><p className="mt-2 text-sm leading-6 text-muted">Map ID, title, mapper, Legacy ID/hash information and the official map file are used to keep the pass tied to the correct analyzed map.</p></div><div className="rounded-2xl border border-border bg-background/70 p-5"><p className="font-semibold text-white">2. Miss locations</p><p className="mt-2 text-sm leading-6 text-muted">Replay cursor frames are aligned with the SSPM/RHM map timeline. The replay&apos;s official miss count is then mapped onto the notes most consistent with those misses.</p></div><div className="rounded-2xl border border-border bg-background/70 p-5"><p className="font-semibold text-white">3. Pattern balance</p><p className="mt-2 text-sm leading-6 text-muted">Misses are grouped into streams, jumps, tech and mixed sections using the map&apos;s stored pattern timeline.</p></div></div></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Balanced passes keep more points</h2><p className="mt-2 text-sm leading-7 text-muted">Two players can finish a map with the same overall accuracy and still earn different points. If one player performs reasonably across every meaningful pattern while another player clears the jump section but collapses through the stream section, the balanced player keeps more of the map&apos;s maximum reward.</p><p className="mt-4 text-sm leading-7 text-muted">The replay-balance system never increases a pass above the analyzed map reward. It can reduce an unusually one-sided pass by up to 30%, with smoothing for small pattern samples and low miss counts so a single miss does not create an extreme penalty.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Replay safety and fallback</h2><p className="mt-2 text-sm leading-7 text-muted">Rhythians only applies the balance reduction when the replay can be matched to the correct Ranked or Legacy map with enough alignment confidence. If Rhythia does not provide a replay URL, the replay is malformed, the map identity does not match, or the cursor alignment is too uncertain, the system keeps the normal analyzed-map points instead of guessing.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">RHP is exact</h2><p className="mt-2 text-sm leading-7 text-muted">There is no hidden placement weighting in the live point total. RHP is simply RPL + RPS + RPV after each eligible pass has been processed. Rhythia RP and global rank can still be displayed as Rhythia account information, but they do not directly create Rhythians ranking points.</p></section>
  </div>;
}
