import { RANKS, RANK_TIERS, getRankInfo, rankTierBounds } from "@/lib/ranks";
import { MODE_RULES } from "@/lib/rhythia-mode-rules";
import { RankIcon } from "@/components/rank-icon";

const modes = [
  { key: "lock", name: "RPL", label: "Lock", scale: MODE_RULES.lock.rankScale, max: MODE_RULES.lock.maxPoints },
  { key: "spin", name: "RPS", label: "Spin", scale: MODE_RULES.spin.rankScale, max: MODE_RULES.spin.maxPoints },
  { key: "vr", name: "RPV", label: "VR", scale: MODE_RULES.vr.rankScale, max: MODE_RULES.vr.maxPoints },
];

export default function AboutRankingPage() {
  return <div className="space-y-8">
    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><p className="text-sm uppercase tracking-[0.3em] text-accent">Ranking system v2</p><h1 className="mt-3 text-3xl font-semibold text-white">RHP, RPL, RPS and RPV</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted">Rhythians separates overall competitive strength from camera-mode skill. RPL measures Lock, RPS measures Spin, RPV measures VR, and RHP combines those mode ratings into the main ranked ladder. This prevents playing several modes from simply tripling a player&apos;s overall rank.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Overall RHP ladder</h2><p className="mt-2 text-sm leading-7 text-muted">Copper through Master each have five tiers. Rank widths increase as players climb so established players have room to separate instead of being compressed into Expert. Expert is one final rank with no numbered tiers.</p><div className="mt-6 overflow-hidden rounded-2xl border border-border"><div className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-3">{RANKS.map(rank => { const next = RANKS[rank.index + 1]; const tierIcons = rank.index === RANKS.length - 1 ? [<RankIcon key="expert" rank={getRankInfo(rank.minRhp)} size={58}/>] : Array.from({ length: RANK_TIERS }, (_, index) => <RankIcon key={index} rank={getRankInfo(rankTierBounds(rank.index, index + 1).start)} size={42}/>); return <div key={rank.name} className="bg-surface p-5"><div className="flex items-center gap-1">{tierIcons}</div><p className="mt-3 text-sm font-semibold" style={{ color: rank.color }}>{rank.name}</p><p className="mt-2 text-xs text-muted">{rank.minRhp.toLocaleString()}{next ? ` – ${(next.minRhp - 1).toLocaleString()}` : "+"} RHP</p><p className="mt-1 text-xs text-muted">Map rating {rank.rangeMin.toFixed(2)} – {rank.rangeMax.toFixed(2)}</p><p className="mt-2 text-[11px] text-muted">{next ? `${RANK_TIERS} dynamic tiers` : "Final rank · no numbered tiers"}</p></div>; })}</div></div></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Mode ratings</h2><p className="mt-2 text-sm leading-7 text-muted">Each ranked clear contributes to the camera mode it was played in. The three ladders use the same rank names but a smaller point scale appropriate to the number of points available from ranked maps.</p><div className="mt-5 grid gap-4 md:grid-cols-3">{modes.map(mode => <div key={mode.key} className="rounded-2xl border border-border bg-background/70 p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-accent">{mode.name}</p><h3 className="mt-2 text-lg font-semibold text-white">{mode.label}</h3><p className="mt-2 text-sm text-muted">Up to {mode.max} points per qualifying clear.</p><p className="mt-1 text-xs text-muted">Rank scale: {(mode.scale * 100).toFixed(0)}% of the RHP ladder.</p></div>)}</div></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">How RHP is calculated</h2><p className="mt-2 text-sm leading-7 text-muted">The three mode ratings are first normalized to the common RHP scale, then ordered from strongest to weakest. Your strongest mode contributes 75% of the skill composite, your second mode 20%, and your third mode 5%. This rewards breadth without allowing three mediocre mode totals to overpower one genuinely strong specialist.</p><div className="mt-5 rounded-2xl border border-border bg-background/70 p-5 text-sm leading-7 text-muted"><p><span className="font-semibold text-white">Strongest mode:</span> 75%</p><p><span className="font-semibold text-white">Second mode:</span> 20%</p><p><span className="font-semibold text-white">Third mode:</span> 5%</p><p className="mt-3">An administrator can tune these placement and weighting controls from the ranking admin panel. The weights are normalized to 100% before use.</p></div></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Veteran placement</h2><p className="mt-2 text-sm leading-7 text-muted">A linked veteran does not have to start beside a brand-new player. Initial placement uses verified Rhythia global rank plus historical Rhythia RP to establish an overall RHP floor. Top-500, 501–1000, 1001–5000 and 5001+ players have separate placement floors, while RP can place a proven player higher. This is a starting floor, not recurring free RHP.</p><p className="mt-4 text-sm leading-7 text-muted">Mode placement is deliberately more conservative. A portion of the overall placement can seed RPL, RPS and RPV when historical mode detection is incomplete, but existing verified mode scores take priority. That keeps veterans out of beginner matchmaking without pretending they are equally skilled in every camera mode.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Ranked maps and eligibility</h2><p className="mt-2 text-sm leading-7 text-muted">Each RPL, RPS and RPV map view uses that mode&apos;s current rank to decide which map rating band is eligible. Score synchronization can discover approved ranked-map history across the catalog; it is no longer limited to maps matching the player&apos;s old overall rank. This removes the circular problem where a player needed a higher rank before the system could discover the scores that should have raised that rank.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">Ranked battles</h2><p className="mt-2 text-sm leading-7 text-muted">RBP remains the seasonal battle rating, but initial RBP placement now starts roughly one tier below the player&apos;s current RHP tier instead of a full rank below. New players still meet other new players, while established competitors enter close enough to their expected level that ranked battles can refine their position instead of forcing a long climb through weaker opponents.</p></section>

    <section className="rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><h2 className="text-2xl font-semibold text-white">RHP and Rhythia RP are different</h2><p className="mt-2 text-sm leading-7 text-muted">Rhythia RP is used as historical evidence for initial placement only. Rhythians RHP is the live competitive rating used for Rhythians leaderboards, map eligibility and matchmaking. After placement, ranked Rhythians performance is what moves the player forward.</p></section>
  </div>;
}
