import { prisma } from "@/lib/db";

export async function ensureCompletionClipTables() {
  await prisma.$executeRawUnsafe(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'CompletionClipStatus') THEN CREATE TYPE "CompletionClipStatus" AS ENUM ('pending','approved','rejected','hidden'); END IF; END $$;`);
  await prisma.$executeRawUnsafe(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid WHERE t.typname = 'CategoryType' AND e.enumlabel = 'vibro') THEN ALTER TYPE "CategoryType" ADD VALUE 'vibro'; END IF; END $$;`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "CompletionClip" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"category" "CategoryType" NOT NULL,"level" INTEGER NOT NULL,"mapName" TEXT NOT NULL,"storagePath" TEXT NOT NULL,"status" "CompletionClipStatus" NOT NULL DEFAULT 'pending',"reviewedById" TEXT,"reviewedAt" TIMESTAMP(3),"reviewerNote" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CompletionClip_pkey" PRIMARY KEY ("id"),CONSTRAINT "CompletionClip_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE,CONSTRAINT "CompletionClip_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL)`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ChallengeCompletionClip" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"level" INTEGER NOT NULL,"mapName" TEXT NOT NULL,"storagePath" TEXT NOT NULL,"status" "CompletionClipStatus" NOT NULL DEFAULT 'pending',"reviewedById" TEXT,"reviewedAt" TIMESTAMP(3),"reviewerNote" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ChallengeCompletionClip_pkey" PRIMARY KEY ("id"),CONSTRAINT "ChallengeCompletionClip_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE,CONSTRAINT "ChallengeCompletionClip_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL)`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "CompletionClip_status_createdAt_idx" ON "CompletionClip"("status","createdAt")`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "CompletionClip_userId_category_level_idx" ON "CompletionClip"("userId","category","level")`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "ChallengeCompletionClip_status_createdAt_idx" ON "ChallengeCompletionClip"("status","createdAt")`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS "ChallengeCompletionClip_userId_level_idx" ON "ChallengeCompletionClip"("userId","level")`);
}
