const RHYTHIA_API_URLS = [process.env.RHYTHIA_API_URL, "https://production.rhythia.com/api"].filter((url): url is string => Boolean(url));

export type RhythiaScore = { id: number; beatmapTitle: string | null; speed: number | null; misses: number | null; beatmapNotes: number | null; awarded_sp: number | null; passed: boolean | null; rank?: string | null; cameraMode?: string | null; camera_mode?: string | null; gameMode?: string | null; game_mode?: string | null; mode?: string | null; playMode?: string | null; play_mode?: string | null; spin?: boolean | number | string | null; vr?: boolean | number | string | null; isVr?: boolean | null; is_vr?: boolean | null; mods?: string | string[] | null; modifiers?: string | string[] | null };
export function parseRhythiaUrl(value:string){try{const url=new URL(value.trim());if(url.protocol!=="https:"||!["rhythia.com","www.rhythia.com"].includes(url.hostname))return null;const match=url.pathname.match(/^\/player\/(\d+)\/?$/);return match?{id:Number(match[1]),url:`https://www.rhythia.com/player/${Number(match[1])}`}:null}catch{return null}}
export function parseRhythiaMapUrl(value:string){try{const url=new URL(value.trim());if(url.protocol!=="https:"||!["rhythia.com","www.rhythia.com"].includes(url.hostname))return null;const match=url.pathname.match(/^\/maps\/(\d+)\/?$/);return match?{id:Number(match[1]),url:`https://www.rhythia.com/maps/${Number(match[1])}`}:null}catch{return null}}
function titleFor(rhythmPoints:number|null,globalRank:number|null){if(globalRank&&globalRank<=30)return"Grandmaster";if((rhythmPoints??0)>10000)return"Candidate Grandmaster";if((rhythmPoints??0)>=5000)return"Master";if((rhythmPoints??0)>=2500)return"Candidate Master";if((rhythmPoints??0)>=1500)return"Expert";return"Novice"}
function buildUrl(baseUrl:string,path:string,body:Record<string,unknown>){const url=new URL(`${baseUrl.replace(/\/$/,"")}/${path}`);for(const[key,value]of Object.entries(body))if(value!==undefined&&value!==null)url.searchParams.set(key,String(value));return url}
async function readApiResponse<T>(response:Response,endpoint:string):Promise<T>{const text=await response.text();const contentType=response.headers.get("content-type")?.toLowerCase()??"";if(!response.ok){const detail=text.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,180);throw new Error(`Rhythia API returned ${response.status}${detail?`: ${detail}`:""}.`)}if(!contentType.includes("json")){if(/^\s*<!doctype html/i.test(text)||/<html[\s>]/i.test(text))throw new Error(`Rhythia API endpoint ${endpoint} returned an HTML page instead of JSON.`);throw new Error(`Rhythia API endpoint ${endpoint} returned a non-JSON response.`)}const data=JSON.parse(text)as T&{error?:string;message?:string};if(data.error)throw new Error(data.error);return data}
async function requestFromApi<T>(baseUrl:string,path:string,body:Record<string,unknown>):Promise<T>{const endpoint=`${baseUrl.replace(/\/$/,"")}/${path}`;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(endpoint,{method:"POST",headers:{accept:"application/json","content-type":"application/json","user-agent":"Rhythians/1.0"},body:JSON.stringify({session:"",...body}),cache:"no-store",signal:controller.signal});if(response.status===405)return readApiResponse<T>(await fetch(buildUrl(baseUrl,path,{session:"",...body}),{method:"GET",headers:{accept:"application/json","user-agent":"Rhythians/1.0"},cache:"no-store",signal:controller.signal}),endpoint);return readApiResponse<T>(response,endpoint)}finally{clearTimeout(timeout)}}
export async function rhythiaRequest<T>(path:string,body:object):Promise<T>{let lastError:unknown=null;const requestBody={...body}as Record<string,unknown>;if(path==="getUserScores"){delete requestBody.offset;delete requestBody.page}for(const baseUrl of RHYTHIA_API_URLS){try{return await requestFromApi<T>(baseUrl,path,requestBody)}catch(error){lastError=error}}if(lastError instanceof Error){if(lastError.name==="AbortError")throw new Error("Rhythia took too long to respond.");throw lastError}throw new Error("Rhythia could not be reached.")}
function normalizeName(name:string|null|undefined){return(name??"").trim().toLowerCase().replace(/[\s_]+/g,"")}
export function namesMatch(rhythiaUsername:string|null,localNames:(string|null|undefined)[]){const target=normalizeName(rhythiaUsername);return Boolean(target)&&localNames.some((name)=>normalizeName(name)===target)}
function findBio(value:unknown):string|null{if(!value||typeof value!=="object")return null;const record=value as Record<string,unknown>;for(const key of["bio","about","aboutMe","about_me","description"])if(typeof record[key]==="string"&&(record[key]as string).trim())return record[key]as string;for(const key of["user","profile","data"]){const nested=findBio(record[key]);if(nested)return nested}return null}
function numericField(record:Record<string,unknown>,keys:string[]){for(const key of keys){const value=record[key];if(typeof value==="number"&&Number.isFinite(value)&&value>=0)return value;if(typeof value==="string"&&value.trim()&&Number.isFinite(Number(value))&&Number(value)>=0)return Number(value)}return null}
function findModeRp(value:unknown):{lock:number;spin:number;vr:number}|null{if(!value||typeof value!=="object")return null;const record=value as Record<string,unknown>;const lock=numericField(record,["lock_rp","lockRp","lockRP","lock_skill_points","lockSkillPoints","skill_points_lock","skillPointsLock","rp_lock","rpLock"]);const spin=numericField(record,["spin_rp","spinRp","spinRP","spin_skill_points","spinSkillPoints","skill_points_spin","skillPointsSpin","rp_spin","rpSpin"]);const vr=numericField(record,["vr_rp","vrRp","vrRP","vr_skill_points","vrSkillPoints","skill_points_vr","skillPointsVr","rp_vr","rpVr"]);if(lock!=null&&spin!=null&&vr!=null)return{lock,spin,vr};for(const key of["user","profile","data","stats","ranked","ranking","rp","skillPoints","skill_points"]){const nested=findModeRp(record[key]);if(nested)return nested}return null}
function enabled(value:unknown){return value===true||value===1||value==="1"||(typeof value==="string"&&["true","yes","on","enabled"].includes(value.toLowerCase()))}
function textValue(value:unknown){return Array.isArray(value)?value.join(" "):typeof value==="string"?value:""}
function scoreMode(score:RhythiaScore,bucket:string){const explicit=`${score.cameraMode??""} ${score.camera_mode??""} ${score.gameMode??""} ${score.game_mode??""} ${score.mode??""} ${score.playMode??""} ${score.play_mode??""}`.toLowerCase();const modifiers=`${textValue(score.mods)} ${textValue(score.modifiers)}`.toLowerCase();if(explicit.includes("vr")||explicit.includes("virtual reality")||enabled(score.vr)||score.isVr===true||score.is_vr===true||bucket.startsWith("vr")||/(^|[^a-z])vr([^a-z]|$)/i.test(modifiers))return"vr"as const;if(explicit.includes("spin")||enabled(score.spin)||/(^|[^a-z])spin([^a-z]|$)/i.test(modifiers))return"spin"as const;return"lock"as const}
function modeRpFromScores(data:Partial<Record<"lastDay"|"top"|"vrTop"|"vrRecent",RhythiaScore[]>>){const best=new Map<number,{score:RhythiaScore;mode:"lock"|"spin"|"vr"}>();for(const bucket of["lastDay","top","vrTop","vrRecent"]as const)for(const score of data[bucket]??[]){if(!score||typeof score.id!=="number")continue;const mode=scoreMode(score,bucket);const old=best.get(score.id);if(!old||old.mode==="lock"&&mode!=="lock"||old.mode!=="vr"&&mode==="vr")best.set(score.id,{score,mode})}const awarded={lock:0,spin:0,vr:0};for(const{score,mode}of best.values())if(score.passed!==false&&typeof score.awarded_sp==="number"&&score.awarded_sp>0)awarded[mode]+=score.awarded_sp;return{lock:awarded.lock/2,spin:awarded.spin/2,vr:awarded.vr/2}}
export async function fetchRhythiaModeRp(id:number){const [profile,scores]=await Promise.all([rhythiaRequest<Record<string,unknown>>("getProfile",{id}),rhythiaRequest<Partial<Record<"lastDay"|"top"|"vrTop"|"vrRecent",RhythiaScore[]>>>("getUserScores",{id,limit:100})]);const direct=findModeRp(profile);if(direct)return direct;const calculated=modeRpFromScores(scores);if(calculated.lock>0||calculated.spin>0||calculated.vr>0)return calculated;const user=profile.user&&typeof profile.user==="object"?profile.user as Record<string,unknown>:null;const overall=user?numericField(user,["skill_points"]):null;if(overall!=null)return{lock:overall,spin:0,vr:0};throw new Error("Rhythia returned no usable RP for this profile.")}
export async function fetchRhythiaProfile(id:number){const profile=await rhythiaRequest<Record<string,unknown>>("getProfile",{id});const user=profile.user&&typeof profile.user==="object"?profile.user as Record<string,unknown>:null;const userId=typeof user?.id==="number"?user.id:null;if(!user||userId!==id)throw new Error("That Rhythia profile was not found.");let scores:RhythiaScore[]=[];try{const scoreData=await rhythiaRequest<{top?:RhythiaScore[]}>("getUserScores",{id,limit:10});scores=scoreData.top??[]}catch{}const username=typeof user.username==="string"?user.username:null;const flag=typeof user.flag==="string"?user.flag:null;const globalRank=typeof user.position==="number"?user.position:null;const countryRank=typeof user.country_position==="number"?user.country_position:null;const rhythmPoints=typeof user.skill_points==="number"?user.skill_points:null;return{profileId:id,username,bio:findBio(profile),country:flag,flag,globalRank,countryRank,rhythmPoints,title:titleFor(rhythmPoints,globalRank),scores}}
