"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Check, Download, Loader2, Swords, Trophy, UserRound, ArrowRight } from "lucide-react";
import { getRankInfo, rankLabel } from "@/lib/ranks";

function Avatar({ player, large = false }: { player: any; large?: boolean }) { const size = large ? "h-20 w-20" : "h-12 w-12"; return player?.avatar ? <img src={player.avatar} alt={player.username} className={`${size} rounded-full border border-border object-cover`} /> : <div className={`${size} flex items-center justify-center rounded-full border border-border bg-accent/10 text-accent`}><UserRound size={large ? 28 : 19} /></div>; }

export function BattleMatchApp({ matchId }: { matchId: string }) {
  const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [checking, setChecking] = useState(false); const [accepting, setAccepting] = useState(false); const [error, setError] = useState(""); const [countdown, setCountdown] = useState(3); const [resultProgress, setResultProgress] = useState(0); const [showResult, setShowResult] = useState(false);
  async function load() { try { const response = await fetch(`/api/battles/matches?id=${encodeURIComponent(matchId)}`, { cache: "no-store" }); const result = await response.json(); if (response.ok) { setData(result); setError(""); } else setError(result.error ?? "Match not found."); } catch { setError("Could not update the battle."); } finally { setLoading(false); } }
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 1500); return () => clearInterval(timer); }, [matchId]);
  useEffect(() => { if (!data?.match?.startedAt || data.match.status !== "active") return; setCountdown(3); const timer = setInterval(() => setCountdown((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [data?.match?.startedAt, data?.match?.status]);
  useEffect(() => { if (data?.match?.status !== "finished" || showResult) return; setShowResult(true); setResultProgress(0); const timer = setInterval(() => setResultProgress((value) => { if (value >= 100) { clearInterval(timer); return 100; } return Math.min(100, value + 5); }), 55); return () => clearInterval(timer); }, [data?.match?.status, showResult]);
  async function checkScore() { setChecking(true); setError(""); const response = await fetch("/api/battles/matches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "check-score", matchId }) }); const result = await response.json(); setChecking(false); if (!response.ok) { setError(result.error ?? "Could not check your score."); return; } await load(); }
  async function accept() { setAccepting(true); setError(""); const response = await fetch("/api/battles/matches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "accept", matchId }) }); const result = await response.json(); setAccepting(false); if (!response.ok) { setError(result.error ?? "Could not accept battle."); return; } await load(); }
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center text-muted"><Loader2 className="mr-2 animate-spin" />Loading battle...</div>;
  if (!data) return <div className="mx-auto max-w-2xl rounded-3xl border border-red-400/20 bg-red-400/10 p-8 text-center text-red-300">{error || "Battle unavailable."}</div>;
  const players = data.players ?? []; const teamOne = players.filter((player: any) => player.team === 1); const teamTwo = players.filter((player: any) => player.team === 2); const mode = String(data.match.mode ?? "1v1").split(":")[0]; const isLarge = mode === "15v15"; const finished = data.match.status === "finished"; const viewer = players.find((player: any) => player.userId === data.viewerId); const waitingForOwnScore = data.match.status === "active" && viewer?.accuracy == null; const teamScores = data.teamScores ?? { one: null, two: null, winner: null }; const canAccept = data.match.status === "invite" && viewer?.team === 2;
  const Tags = ({ player }: { player: any }) => <div className="mt-1 flex flex-wrap gap-1">{(Array.isArray(player?.tags) ? player.tags : []).slice(0, 3).map((tag: any) => <span key={tag.slug} className="rounded-lg border border-accent/30 bg-accent/10 px-2.5 py-1 text-xs font-bold text-accent">{tag.name}</span>)}</div>;
  const Team = ({ team, label }: { team: any[]; label: string }) => <div className="flex-1 rounded-3xl border border-border bg-surface/95 p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-accent">{label}</p><p className="mt-1 text-sm text-muted">{team.length} players</p></div><Trophy className="text-accent" size={20} /></div><div className={isLarge ? "grid grid-cols-3 gap-2" : "space-y-3"}>{team.map((player: any) => { const rank = getRankInfo(player.rhp); return <Link href={`/profile/${encodeURIComponent(player.profileHandle)}`} key={player.userId} className={`group flex items-center gap-3 rounded-2xl border border-border bg-background/40 p-3 transition hover:border-accent/30 ${isLarge ? "flex-col text-center" : ""}`}><Avatar player={player} large={!isLarge && mode === "1v1"} /><div className="min-w-0 flex-1"><p className="truncate font-semibold text-white group-hover:text-accent">{player.displayName ?? player.username}</p>{!isLarge && <><Tags player={player} /><span className="mt-1 inline-flex rounded-full border border-border px-2 py-0.5 text-[10px] font-semibold" style={{ color: rank.color }}>{rankLabel(rank)}</span></>}{player.accuracy != null && <p className="mt-1 text-xs text-muted">{Number(player.accuracy).toFixed(2)}%</p>}</div></Link>; })}</div></div>;
  const MapPanel = () => data.map && <section className="rounded-3xl border border-border bg-surface/95 p-6 shadow-glow"><div className="flex flex-wrap items-center gap-5">{data.map.imageUrl && <img src={data.map.imageUrl} alt="" className="h-24 w-24 rounded-2xl object-cover" />}<div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-[0.2em] text-accent">Battle map</p><h2 className="mt-1 text-xl font-semibold text-white">{data.map.title}</h2><p className="mt-1 text-sm text-muted">{data.map.artist ?? ""}{data.map.rating != null ? ` · ${Number(data.map.rating).toFixed(2)}★` : ""}</p></div>{data.map.mapFileUrl && <a href={data.map.mapFileUrl} className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2.5 text-sm font-semibold text-white hover:border-accent/40"><Download size={16} /> Download map</a>}{!finished && <button disabled={checking || countdown > 0} onClick={checkScore} className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{checking ? <Loader2 className="animate-spin" size={16} /> : <Check size={16} />} Check score</button>}</div>{error && <p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}</section>;
  const Waiting = () => <section className="mx-auto w-full max-w-4xl rounded-3xl border border-border bg-surface/95 p-8 shadow-glow"><div className="grid items-center gap-6 md:grid-cols-[1fr_auto_1fr]"><div className="flex flex-col items-center rounded-3xl border border-accent/20 bg-accent/5 p-7 text-center"><Avatar player={teamOne[0]} large /><p className="mt-4 font-semibold text-white">{teamOne[0]?.displayName ?? teamOne[0]?.username}</p><Tags player={teamOne[0]} /><span className="mt-2 text-xs text-muted">{teamOne[0] ? rankLabel(getRankInfo(teamOne[0].rhp)) : ""}</span></div><div className="flex flex-col items-center gap-3"><div className="flex h-20 w-20 items-center justify-center rounded-full border border-accent/30 bg-accent/10 text-2xl font-black italic text-accent">VS</div><span className="text-xs uppercase tracking-[0.18em] text-muted">{canAccept ? "Challenge" : "Waiting"}</span></div><div className="flex flex-col items-center rounded-3xl border border-border bg-background/40 p-7 text-center"><Avatar player={teamTwo[0]} large /><p className="mt-4 font-semibold text-white">{teamTwo[0]?.displayName ?? teamTwo[0]?.username}</p><Tags player={teamTwo[0]} />{canAccept ? <button disabled={accepting} onClick={accept} className="mt-4 inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{accepting ? <Loader2 size={15} className="animate-spin" /> : <Check size={15} />} Accept 1v1</button> : <p className="mt-2 text-xs text-muted">Waiting for the other player to accept.</p>}</div></div>{error && <p className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}</section>;
  const Result = () => { const winner = teamScores.winner; const visibleOne = teamScores.one == null ? 0 : teamScores.one * resultProgress / 100; const visibleTwo = teamScores.two == null ? 0 : teamScores.two * resultProgress / 100; return <section className="overflow-hidden rounded-3xl border border-accent/30 bg-surface/95 p-8 shadow-glow"><div className="text-center"><p className="text-xs uppercase tracking-[0.24em] text-accent">Final score</p><h2 className="mt-2 text-3xl font-semibold text-white">{winner === 0 ? "Draw" : winner === 1 ? "Team 1 wins" : "Team 2 wins"}</h2></div><div className="mt-8 grid gap-4 md:grid-cols-[1fr_auto_1fr]"><div className={`rounded-3xl border p-6 text-center transition ${winner === 1 ? "border-accent bg-accent/10 scale-[1.02]" : "border-border bg-background/40"}`}><p className="text-sm font-semibold text-muted">Team 1</p><p className="mt-2 text-5xl font-black tabular-nums text-white">{visibleOne.toFixed(2)}%</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-background"><div className="h-full rounded-full bg-accent transition-all duration-75" style={{ width: `${resultProgress}%` }} /></div></div><div className="flex items-center justify-center text-2xl font-black italic text-muted">VS</div><div className={`rounded-3xl border p-6 text-center transition ${winner === 2 ? "border-accent bg-accent/10 scale-[1.02]" : "border-border bg-background/40"}`}><p className="text-sm font-semibold text-muted">Team 2</p><p className="mt-2 text-5xl font-black tabular-nums text-white">{visibleTwo.toFixed(2)}%</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-background"><div className="h-full rounded-full bg-accent transition-all duration-75" style={{ width: `${resultProgress}%` }} /></div></div></div><div className={`mt-6 text-center transition duration-500 ${resultProgress >= 100 ? "translate-y-0 opacity-100" : "translate-y-3 opacity-0"}`}><p className="text-sm text-muted">{data.match.matchType === "ranked" ? "Ranked rewards have been processed." : "Casual battle complete."}</p><Link href="/battles/history" className="mt-3 inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-white">Battle history <ArrowRight size={15} /></Link></div></section>; };
  return <div className="mx-auto max-w-7xl space-y-5"><section className="rounded-3xl border border-border bg-surface/95 p-6 shadow-glow"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.22em] text-accent"><Swords size={15} /> {data.match.matchType} battle</p><h1 className="mt-2 text-3xl font-semibold text-white">{mode}</h1><p className="mt-1 text-sm text-muted">{data.match.status === "queue" ? "Searching for opponents..." : data.match.status === "invite" ? "Waiting for the opponent to accept." : finished ? "Battle complete" : "Map battle"}</p></div>{data.match.status === "active" && countdown > 0 && <div className="flex h-14 w-14 items-center justify-center rounded-full border border-accent/40 bg-accent/10 text-2xl font-bold text-accent">{countdown}</div>}</div></section>{data.match.status === "queue" ? <section className="rounded-3xl border border-border bg-surface/95 p-12 text-center shadow-glow"><Loader2 className="mx-auto animate-spin text-accent" size={34} /><h2 className="mt-5 text-xl font-semibold text-white">Finding your battle</h2><p className="mt-2 text-sm text-muted">{data.match.matchType === "ranked" ? "Waiting for players in your exact rank and tier." : "Waiting for players in your rank."}</p></section> : data.match.status === "invite" ? <Waiting /> : waitingForOwnScore ? <><section className="mx-auto max-w-xl rounded-3xl border border-accent/20 bg-surface/95 p-8 text-center shadow-glow"><Avatar player={viewer} large /><p className="mt-5 text-xs uppercase tracking-[0.2em] text-accent">Your battle</p><h2 className="mt-2 text-2xl font-semibold text-white">{viewer?.displayName ?? viewer?.username}</h2><Tags player={viewer} /><p className="mt-3 text-sm text-muted">Complete the battle map, then check your recent Rhythia score.</p></section>{MapPanel()}</> : finished && showResult ? <Result /> : <><section className="flex flex-col gap-5 lg:flex-row"><Team team={teamOne} label="Team 1" /><div className="flex items-center justify-center px-2 text-4xl font-black italic text-muted">VS</div><Team team={teamTwo} label="Team 2" /></section>{MapPanel()}</>}</div>;
}
