import Link from "next/link";
import { CircleUserRound, Link2, LogIn, Users } from "lucide-react";
import { getSessionUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { getOnlineGlobalRankedUsers } from "@/lib/online-users";
import { getRankInfo } from "@/lib/ranks";

export const dynamic = "force-dynamic";

export default async function OnlinePage() {
  const user = await getSessionUser();
  if (!user) return <div className="mx-auto max-w-3xl py-8"><section className="rounded-3xl border border-border bg-surface/95 p-10 text-center shadow-glow"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-accent/15 text-accent"><LogIn size={26} /></div><h1 className="mt-5 text-2xl font-semibold text-white">Sign in to see online users</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted">Online users are available to members with a linked Rhythia account.</p><Link href="/login" className="mt-6 inline-flex items-center gap-2 rounded-full bg-accent px-6 py-3 text-sm font-semibold text-white"><LogIn size={16} /> Sign in</Link></section></div>;

  const profile = await prisma.rhythiaProfile.findUnique({ where: { userId: user.id }, select: { id: true } });
  if (!profile) return <div className="mx-auto max-w-3xl py-8"><section className="rounded-3xl border border-border bg-surface/95 p-10 text-center shadow-glow"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-accent/15 text-accent"><Link2 size={26} /></div><h1 className="mt-5 text-2xl font-semibold text-white">Link your Rhythia account</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted">Link your Rhythia profile before viewing the online list.</p><Link href={`/profile/${user.profileHandle}`} className="mt-6 inline-flex items-center gap-2 rounded-full bg-accent px-6 py-3 text-sm font-semibold text-white"><Link2 size={16} /> Go to my profile</Link></section></div>;

  const users = await getOnlineGlobalRankedUsers();

  return <div className="mx-auto max-w-5xl space-y-8 py-2"><section className="space-y-3"><p className="flex items-center gap-2 text-sm uppercase tracking-[0.24em] text-accent"><Users size={16} /> Online</p><div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold text-white">Online users</h1><p className="mt-2 text-sm leading-7 text-muted">Online players sorted by their place on the entire global ranked leaderboard. Their main Challenge Level is shown beside their ranked tier.</p></div><span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-200">{users.length} online</span></div></section>{users.length === 0 ? <section className="rounded-3xl border border-border bg-surface/95 p-10 text-center shadow-glow"><CircleUserRound className="mx-auto text-muted" size={32} /><p className="mt-4 text-sm text-muted">No users are currently online.</p></section> : <section className="overflow-hidden rounded-3xl border border-border bg-surface/95 shadow-glow"><div className="divide-y divide-border">{users.map((onlineUser) => { const rank = getRankInfo(onlineUser.rhp); return <Link key={onlineUser.id} href={`/profile/${onlineUser.profileHandle}`} className="flex items-center gap-4 px-4 py-4 transition hover:bg-white/[0.03] sm:px-6"><div className="flex w-10 shrink-0 items-center justify-center text-sm font-bold text-muted">#{onlineUser.globalPosition ?? "-"}</div><div className="relative shrink-0"><div className="h-12 w-12 overflow-hidden rounded-full border border-border bg-background">{onlineUser.avatar ? <img src={onlineUser.avatar} alt={onlineUser.displayName ?? onlineUser.username} className="h-full w-full object-cover" /> : <div className="flex h-full w-full items-center justify-center text-muted"><CircleUserRound size={24} /></div>}</div><span className="absolute bottom-0 right-0 h-3.5 w-3.5 rounded-full border-2 border-surface bg-emerald-400" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{onlineUser.displayName ?? onlineUser.username}</p><p className="truncate text-xs text-muted">{onlineUser.title}</p></div><div className="hidden min-w-28 text-right sm:block"><p className="text-xs uppercase tracking-[0.18em] text-muted">Ranked</p><p className="mt-1 text-sm font-semibold" style={{ color: rank.color }}>{rank.name} {rank.tier}</p></div><div className="min-w-24 text-right"><p className="text-xs uppercase tracking-[0.18em] text-muted">Challenge</p><p className="mt-1 text-sm font-semibold text-white">Level {onlineUser.challengeLevel}</p></div></Link>; })}</div></section>}</div>;
}
