import Link from "next/link";
import { ArrowRight, Link2, Lock, Trophy } from "lucide-react";
import { prisma } from "@/lib/db";
import { getSessionUser } from "@/lib/auth";
import { getDailyLeaderboard } from "@/lib/daily";
import { RANKS, getRankInfo } from "@/lib/ranks";
import { RankIcon } from "@/components/rank-icon";

export async function HomeLeaderboardSection() {
  const user = await getSessionUser();
  if (!user) return <section className="rounded-3xl border border-border bg-surface/95 p-6 shadow-glow"><div className="flex items-center gap-3 text-sm uppercase tracking-[0.24em] text-accent"><Trophy size={18} /> Leaderboards</div><div className="mt-6 flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-accent/15 text-accent"><Lock size={24} /></div><div><h3 className="text-lg font-semibold text-white">Sign in to see the standings</h3><p className="mt-2 text-sm leading-6 text-muted">Daily and challenge leaderboards track the members who beat the most maps for Rhythian Points.</p><Link href="/login" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-accent transition hover:text-white">Sign in <ArrowRight size={16} /></Link></div></div></section>;

  const profile = await prisma.rhythiaProfile.findUnique({ where: { userId: user.id }, select: { id: true } });
  if (!profile) return <section className="rounded-3xl border border-border bg-surface/95 p-6 shadow-glow"><div className="flex items-center gap-3 text-sm uppercase tracking-[0.24em] text-accent"><Trophy size={18} /> Leaderboards</div><div className="mt-6 flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-accent/15 text-accent"><Link2 size={24} /></div><div><h3 className="text-lg font-semibold text-white">Link your Rhythia account to compete</h3><p className="mt-2 text-sm leading-6 text-muted">Leaderboards are reserved for members with a linked Rhythia profile.</p><Link href={`/profile/${user.profileHandle}`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-accent transition hover:text-white">Link your account <ArrowRight size={16} /></Link></div></div></section>;

  const rankBoards = await Promise.all(RANKS.map((rank) => getDailyLeaderboard(rank.index, 100)));
  const rows = rankBoards.flat().sort((a, b) => b.streak - a.streak || b.lastBeatAt.getTime() - a.lastBeatAt.getTime()).slice(0, 5).map((row, index) => ({ ...row, position: index + 1 }));

  return <section className="rounded-3xl border border-border bg-surface/95 p-6 shadow-glow"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3 text-sm uppercase tracking-[0.24em] text-accent"><Trophy size={18} /> Daily leaderboard</div><Link href="/leaderboards" className="inline-flex items-center gap-1 text-sm font-semibold text-accent transition hover:text-white">View leaderboard <ArrowRight size={15} /></Link></div><div className="mt-2 flex items-center gap-3 text-sm text-muted"><Trophy size={16} /><span>Global daily streaks across every Rhythian rank.</span></div><div className="mt-5 space-y-2">{rows.length === 0 ? <p className="rounded-2xl border border-border bg-background/70 p-5 text-sm text-muted">No daily maps have been beaten yet.</p> : rows.map((row) => <div key={row.userId} className="flex items-center gap-3 rounded-2xl border border-border bg-background/70 px-4 py-3"><span className="w-6 text-center text-sm font-bold text-muted">{row.position}</span><RankIcon rank={row.rankInfo} size={38} /><div className="min-w-0 flex-1"><Link href={`/profile/${row.profileHandle}`} className="truncate text-sm font-semibold text-white hover:text-accent">{row.displayName ?? row.username}</Link><p className="text-xs text-muted">{row.rankInfo.isExpert ? "Expert" : `${row.rankInfo.name} ${row.rankInfo.tier}`} · {row.rhp.toLocaleString()} RHP</p></div><span className="text-sm font-semibold text-white">{row.streak}</span><span className="text-xs text-muted">day{row.streak === 1 ? "" : "s"}</span></div>)}</div></section>;
}
