import Link from "next/link";
import { Trophy } from "lucide-react";
import { getRbpLeaderboards } from "@/lib/rbp";
import { RANKS, type RankInfo } from "@/lib/ranks";
import { RankIcon } from "@/components/rank-icon";

function rankInfoFor(index: number): RankInfo {
  const rank = RANKS[index] ?? RANKS[0];
  return { index, name: rank.name, tier: 1, isExpert: index === RANKS.length - 1, minRhp: rank.minRhp, maxRhp: index < RANKS.length - 1 ? rank.minRhp + 500 : null, tierStart: rank.minRhp, tierEnd: rank.minRhp + 100, nextTierStart: rank.minRhp + 100, nextRankStart: index < RANKS.length - 1 ? rank.minRhp + 500 : null, color: rank.color, progressToNextTier: 0, rangeMin: rank.rangeMin, rangeMax: rank.rangeMax };
}

export async function RbpLeaderboards() {
  const data = await getRbpLeaderboards(100);
  if (!data.season) return null;
  return <section className="space-y-5 rounded-[2rem] border border-rose-400/20 bg-[linear-gradient(145deg,rgba(244,63,94,0.07),rgba(20,27,45,0.94))] p-5 shadow-glow sm:p-7"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.22em] text-rose-300"><Trophy size={15} /> Ranked Battle Points</p><h2 className="mt-2 text-2xl font-semibold text-white">Season {data.season.seasonNumber} RBP standings</h2><p className="mt-2 text-sm text-muted">Global rankings compare total RBP. Rank boards compare players within each current RBP rank.</p></div><Link href="/battles" className="text-xs font-semibold text-accent hover:text-white">Battle ladder →</Link></div><div className="grid gap-5 xl:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]"><div className="rounded-3xl border border-white/10 bg-black/15 p-4"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold text-white">Global RBP</h3><span className="text-xs text-muted">Top {data.global.length}</span></div><div className="space-y-1.5">{data.global.slice(0,20).map((row) => <Link key={row.userId} href={`/profile/${row.profileHandle}`} className="flex items-center gap-3 rounded-2xl px-3 py-2.5 transition hover:bg-white/[0.04]"><span className="w-7 text-center text-xs font-bold text-muted">{row.position}</span><RankIcon rank={row.rank} size={34} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{row.displayName ?? row.username}</p><p className="text-[11px]" style={{ color: row.rank.color }}>{row.rank.isExpert ? "Expert" : `${row.rank.name} ${row.rank.tier}`}</p></div><span className="text-sm font-black tabular-nums text-white">{row.rbp}</span></Link>)}</div></div><div className="grid gap-3 sm:grid-cols-2">{RANKS.map((rank, index) => { const rows = data.ranks[index] ?? []; return <div key={rank.name} className="rounded-3xl border border-white/10 bg-black/10 p-4"><div className="mb-3 flex items-center gap-2"><RankIcon rank={rankInfoFor(index)} size={30} /><h3 className="text-sm font-semibold text-white">{rank.name}</h3></div>{rows.length === 0 ? <p className="text-xs text-muted">No players</p> : <div className="space-y-1">{rows.slice(0,5).map((row) => <Link key={row.userId} href={`/profile/${row.profileHandle}`} className="flex items-center gap-2 rounded-xl px-2 py-1.5 hover:bg-white/[0.04]"><span className="w-4 text-[10px] text-muted">{row.position}</span><span className="min-w-0 flex-1 truncate text-xs font-semibold text-white">{row.displayName ?? row.username}</span><span className="text-xs font-bold tabular-nums" style={{ color: row.rank.color }}>{row.rbp}</span></Link>)}</div>}</div>})}</div></div></section>;
}
