"use client";

import { useCallback, useEffect, useState } from "react";
import { Activity, ChevronLeft, ChevronRight, RefreshCw, RotateCcw, Search, ShieldCheck, ShieldOff } from "lucide-react";

type Source = "all" | "ranked" | "unranked" | "legacy";
type Stats = { total: number; analyzed: number; failed: number; pending: number; analyzerVersion: number; source: Source };
type Factor = { key: string; label: string; score: number; reason: string };
type Rankability = { version: number; score: number; confidence: number; verdict: string; summary: string; factors: Factor[]; limitations: string[] };
type Details = { coreDifficulty:number; sustainedDifficulty:number; peakDifficulty:number; movementPressure:number; directionPressure:number; distancePressure:number; timingPressure:number; jumpPressure:number; streamPressure:number; techPressure:number; cheeseRatio:number; activeDuty:number; recoveryRatio:number; difficultyConsistency:number; coverage:{easy:number;moderate:number;hard:number;peak:number}; windows:{micro:number;short:number;medium:number;long:number} };
type Analysis = { analyzerVersion:number; status:string; pointEligible:boolean; analysisDetails:Details|null };
type Fit = { category:string; label:string; score:number; suggestedLevel:number; reason:string };
type Row = { id:string; title:string; artist:string|null; mapperName:string|null; imageUrl:string|null; rating:number|null; sourceStatus:"ranked"|"unranked"|"legacy"; analysisStatus:string; analysis:Analysis|null; rankability:Rankability|null; challengeFits:Fit[] };
type Catalog = { maps:Row[]; page:number; pages:number; total:number; analyzerVersion:number; rankabilityVersion:number; challengeFitVersion:number };

const sourceOptions: Array<[Source,string]> = [["all","All"],["ranked","Ranked"],["unranked","Unranked"],["legacy","Legacy"]];
const pct=(value:number|undefined|null)=>`${Math.round(Math.max(0,Math.min(1,Number(value)||0))*100)}%`;
const num=(value:number|undefined|null)=>Number.isFinite(Number(value))?Number(value).toFixed(2):"—";

export function RankabilityV5Manager(){
  const [source,setSource]=useState<Source>("all"); const [query,setQuery]=useState(""); const [applied,setApplied]=useState(""); const [page,setPage]=useState(1);
  const [catalog,setCatalog]=useState<Catalog|null>(null); const [stats,setStats]=useState<Record<string,Stats|null>>({}); const [busy,setBusy]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState("");

  const load=useCallback(async()=>{ setError(""); const p=new URLSearchParams({source,page:String(page)}); if(applied)p.set("q",applied); try{
    const [catalogRes,rankedRes,unrankedRes,legacyRes]=await Promise.all([
      fetch(`/api/admin/maps/catalog?${p}`,{cache:"no-store"}), fetch("/api/admin/maps/analyze-ranked?source=ranked",{cache:"no-store"}), fetch("/api/admin/maps/analyze-ranked?source=unranked",{cache:"no-store"}), fetch("/api/admin/maps/analyze-ranked?source=legacy",{cache:"no-store"})]);
    const data=await catalogRes.json(); if(!catalogRes.ok)throw new Error(data.error??"Could not load map catalog."); setCatalog(data);
    const next:Record<string,Stats|null>={}; for(const [key,res] of [["ranked",rankedRes],["unranked",unrankedRes],["legacy",legacyRes]] as const){if(res.ok)next[key]=(await res.json()).stats??null;} setStats(next);
  }catch(e){setError(e instanceof Error?e.message:"Could not load map catalog.");}},[source,page,applied]);
  useEffect(()=>{void load();},[load]);

  async function analyzeOne(id:string){setBusy(id);setError("");try{const res=await fetch(`/api/admin/maps/${id}/analyze`,{method:"POST"});const data=await res.json();if(!res.ok)throw new Error(data.error??"Analysis failed.");setMessage(`Rebuilt Difficulty v5, Rankability v5, and Challenge Fit v2. Recalculated ${data.recalculatedUsers??0} affected players.`);await load();}catch(e){setError(e instanceof Error?e.message:"Analysis failed.");}finally{setBusy("");}}
  async function analyzePending(target:Exclude<Source,"all">){if(busy)return;setBusy(`pending:${target}`);setError("");let ok=0,failed=0;try{for(;;){const res=await fetch("/api/admin/maps/analyze-ranked",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:target,limit:2})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Analysis failed.");ok+=data.succeeded??0;failed+=data.failed??0;setMessage(`${target}: ${data.stats?.analyzed??ok}/${data.stats?.total??"?"} current · ${data.stats?.pending??0} pending · ${data.stats?.failed??failed} failed.`);if(!data.processed||!data.stats?.pending)break;}await load();}catch(e){setError(e instanceof Error?e.message:"Analysis failed.");}finally{setBusy("");}}
  async function forceRanked(){if(busy||!window.confirm("Re-analyze every ranked map from raw map data with the newest analyzer suite?"))return;setBusy("force");setError("");let cursor:string|null=null,processed=0,ok=0,failed=0,recalc=0;try{for(;;){const res=await fetch("/api/admin/maps/analyze-ranked",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:"ranked",limit:2,force:true,cursor})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Full rebuild failed.");processed+=data.processed??0;ok+=data.succeeded??0;failed+=data.failed??0;recalc+=data.recalculatedUsers??0;cursor=data.nextCursor??null;setMessage(`Full ranked rebuild: ${processed}/${data.stats?.total??"?"} processed · ${ok} rebuilt · ${failed} failed · ${recalc} player recalculations.`);if(!data.processed||data.done||!cursor)break;}setMessage(`Full ranked rebuild complete: ${ok} rebuilt from raw map data, ${failed} failed, ${recalc} player recalculations.`);await load();}catch(e){setError(e instanceof Error?e.message:"Full rebuild failed.");}finally{setBusy("");}}
  async function togglePoints(row:Row){if(!row.analysis)return;setBusy(row.id);try{const res=await fetch(`/api/admin/maps/${row.id}/eligibility`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({pointEligible:!row.analysis.pointEligible})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Could not update eligibility.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not update eligibility.");}finally{setBusy("");}}

  return <section className="rounded-3xl border border-border bg-surface/95 p-6 shadow-glow sm:p-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.3em] text-accent">Whole-map analyzer suite</p><h2 className="mt-2 text-2xl font-semibold text-white">Difficulty v5 · Rankability v5 · Challenge Fit v2</h2><p className="mt-2 max-w-5xl text-sm leading-6 text-muted">Reads SSPM/RHM/JSON/text note data directly. Timing, three-note direction, logistic spacing, local NPS, bursts, sustained windows, recovery, stamina, pattern recurrence and anti-cheese behavior are evaluated before the final ratings.</p></div><div className="rounded-2xl border border-accent/25 bg-accent/10 px-4 py-3 text-right"><p className="text-xs text-muted">Versions</p><p className="font-bold text-white">D{catalog?.analyzerVersion??5} · R{catalog?.rankabilityVersion??5} · C{catalog?.challengeFitVersion??2}</p></div></div>
    <div className="mt-5 grid gap-3 md:grid-cols-3">{(["ranked","unranked","legacy"] as const).map(key=>{const s=stats[key];return <div key={key} className="rounded-2xl border border-border bg-background/55 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-muted">{key}</p><p className="mt-1 text-lg font-semibold text-white">{s?`${s.analyzed}/${s.total}`:"—"}</p><p className="text-[11px] text-muted">{s?`${s.pending} pending · ${s.failed} failed`:"Loading…"}</p></div><button disabled={Boolean(busy)} onClick={()=>void analyzePending(key)} className="rounded-xl bg-accent px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">{busy===`pending:${key}`?"Analyzing…":"Analyze pending"}</button></div></div>})}</div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-300/25 bg-amber-300/[0.06] p-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-amber-200">Full ranked rebuild</p><p className="mt-1 text-xs text-muted">Forces every ranked map through the newest raw-data analyzer, including maps already marked current.</p></div><button disabled={Boolean(busy)} onClick={()=>void forceRanked()} className="inline-flex items-center gap-2 rounded-xl border border-amber-300/30 bg-amber-300/10 px-4 py-2.5 text-xs font-bold text-amber-100 disabled:opacity-40"><RotateCcw size={15}/>{busy==="force"?"Re-analyzing all ranked…":"Re-analyze ALL ranked with latest"}</button></div>
    <div className="mt-6 flex flex-col gap-3 lg:flex-row"><div className="flex flex-wrap gap-2">{sourceOptions.map(([key,label])=><button key={key} onClick={()=>{setSource(key);setPage(1)}} className={`rounded-full border px-4 py-2 text-xs font-semibold ${source===key?"border-accent bg-accent/15 text-white":"border-border text-muted"}`}>{label}</button>)}</div><form onSubmit={e=>{e.preventDefault();setApplied(query.trim());setPage(1)}} className="flex min-w-0 flex-1 gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, artist, or mapper" className="min-w-0 flex-1 rounded-xl border border-border bg-background px-4 py-2 text-sm text-white"/><button className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-sm font-semibold text-white"><Search size={15}/>Search</button></form><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm text-white"><RefreshCw size={15}/>Refresh</button></div>
    {error&&<p className="mt-4 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{message&&<p className="mt-4 rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-3 text-sm text-emerald-200">{message}</p>}
    <div className="mt-6 space-y-4">{catalog?.maps.map(row=>{const d=row.analysis?.analysisDetails;const fits=[...(row.challengeFits??[])].sort((a,b)=>b.score-a.score).slice(0,3);return <article key={row.id} className="rounded-2xl border border-border bg-background/50 p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-start"><div className="flex min-w-0 flex-1 gap-3">{row.imageUrl?<img src={row.imageUrl} alt="" className="h-16 w-28 rounded-xl object-cover"/>:<div className="h-16 w-28 rounded-xl border border-border"/>}<div className="min-w-0"><h3 className="truncate font-semibold text-white">{row.title}</h3><p className="text-xs text-muted">{row.artist??"Unknown artist"} · {row.mapperName??"Unknown mapper"}</p><div className="mt-2 flex gap-2 text-[10px]"><span className="rounded-full border border-border px-2 py-1 capitalize">{row.sourceStatus}</span><span className="rounded-full border border-border px-2 py-1">{row.analysisStatus}</span>{row.rating!=null&&<span className="rounded-full border border-border px-2 py-1">Difficulty {row.rating.toFixed(2)}</span>}</div></div></div><div className="rounded-2xl border border-accent/25 bg-accent/[0.08] p-4"><p className="text-[10px] uppercase text-muted">Rankability v{row.rankability?.version??5}</p><p className="text-2xl font-black text-white">{row.rankability?.score.toFixed(2)??"—"} / 5</p><p className="text-xs text-accent">{row.rankability?.verdict??"Analyze to score"}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy===row.id} onClick={()=>void analyzeOne(row.id)} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-xs font-semibold text-white"><Activity size={14}/>{busy===row.id?"Working…":"Analyze again"}</button>{row.sourceStatus==="ranked"&&row.analysis&&<button onClick={()=>void togglePoints(row)} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-xs text-white">{row.analysis.pointEligible?<ShieldOff size={14}/>:<ShieldCheck size={14}/>} {row.analysis.pointEligible?"Disable points":"Enable points"}</button>}</div></div>
      {d&&<><div className="mt-4 grid gap-2 border-t border-border pt-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">{[["Core",num(d.coreDifficulty)],["Sustained",num(d.sustainedDifficulty)],["Peak",num(d.peakDifficulty)],["Movement",pct(d.movementPressure)],["Direction",pct(d.directionPressure)],["Distance",pct(d.distancePressure)],["Timing",num(d.timingPressure)],["Jump",num(d.jumpPressure)],["Stream",num(d.streamPressure)],["Tech",num(d.techPressure)],["Anti-cheese",pct(1-d.cheeseRatio)],["Consistency",pct(d.difficultyConsistency)]].map(([label,value])=><div key={label} className="rounded-xl border border-border bg-black/10 p-3"><p className="text-[10px] uppercase text-muted">{label}</p><p className="mt-1 text-sm font-bold text-white">{value}</p></div>)}</div><div className="mt-3 rounded-xl border border-border bg-black/10 p-3 text-xs text-muted">Coverage: easy {pct(d.coverage.easy)} · moderate {pct(d.coverage.moderate)} · hard {pct(d.coverage.hard)} · peak {pct(d.coverage.peak)}. Windows: {num(d.windows.micro)} / {num(d.windows.short)} / {num(d.windows.medium)} / {num(d.windows.long)}. Active {pct(d.activeDuty)} · recovery {pct(d.recoveryRatio)}.</div></>}
      {fits.length>0&&<div className="mt-3 grid gap-2 md:grid-cols-3">{fits.map(f=><div key={f.category} className="rounded-xl border border-cyan-400/20 bg-cyan-400/[0.05] p-3"><div className="flex justify-between"><p className="text-xs font-semibold text-white">{f.label}</p><p className="text-xs font-black text-cyan-200">{f.score.toFixed(2)}/5 · L{f.suggestedLevel}</p></div><p className="mt-1 text-[10px] leading-4 text-muted">{f.reason}</p></div>)}</div>}
      {row.rankability&&<div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4">{row.rankability.factors.map(f=><div key={f.key} className="rounded-xl border border-border bg-black/10 p-3"><div className="flex justify-between"><p className="text-xs font-semibold text-white">{f.label}</p><p className="text-xs font-black text-accent">{f.score.toFixed(2)}/5</p></div><p className="mt-1 text-[10px] leading-4 text-muted">{f.reason}</p></div>)}</div>}</article>})}</div>
    {catalog&&catalog.pages>1&&<div className="mt-6 flex items-center justify-between"><button disabled={page<=1} onClick={()=>setPage(v=>Math.max(1,v-1))} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm text-white disabled:opacity-40"><ChevronLeft size={15}/>Previous</button><p className="text-xs text-muted">Page {catalog.page}/{catalog.pages} · {catalog.total} maps</p><button disabled={page>=catalog.pages} onClick={()=>setPage(v=>v+1)} className="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm text-white disabled:opacity-40">Next<ChevronRight size={15}/></button></div>}
  </section>;
}
